### ISSUE TITLE
reprint count for medium and high

### ISSUE THREAD

**Issue by CarolinOdebrecht** [distantreading/WG1#27]
We have different regulations on the reprint count:

The ODD says: 
                                    <valItem ident="high">
                                        <desc>text has been republished very frequently since its
                                            original appearance</desc>
                                    </valItem>
                                    <valItem ident="medium">
                                        <desc>text has been republished occasionally since its
                                            original appearance</desc>
                                    </valItem>
                                    <valItem ident="low">
                                        <desc>text has not been reprinted since its original
                                            appearance</desc>
                                    </valItem>

The sampling document says: 

                    <item>low: no reprints at all,</item>
                    <item>medium: reprinted once,</item>
                    <item>high: reprinted more than once,</item>
                    <item>We will not include digitizations of texts in the reprint
                        count.</item>

This is crucial for "medium" and "high" The sampling document version is more restricted but clearer. It might be easier to just approximate reprint counts. We cannot assum that occasionally is the same for every language.

**Comment by CarolinOdebrecht** [comment]
This is linked with https://github.com/distantreading/WG1/issues/21

**Comment by lb42** [comment]
Certainly the ODD and the documentation should be in step! We don't seem to have yet reached any clear consensus on what counts as "high" or "low",  and the numbers are likely to be different in different contexts anyway. We do  however agree that we need those two values at least. 

I propose to 
- allow the value  "unmarked",  for texts where the encoder hasn't yet tried to assess the canonicity
- retain value "high" for texts " frequently reprinted during the period"
- retain value "low" for texts "rarely or never reprinted during the period" 

At present the schema also allows for "medium", Should we keep that or change it to "unmarked"  if used?

**Comment by CarolinOdebrecht** [comment]
A binary decision is easier to handle. Introducing a category "unmarked" is also a good idea.

**Comment by lb42** [comment]
So, at present, we allow high, low, unmarked, and unspecified. But if the value is unmarked it is ipso facto unspecified. And if after doing their best an encoder can only say something is unspecified, the effect for the user is just the same as if it was unmarked. So I am removing "unspecified" from the list of possible values. I'll also make the headChecker script convert any "unspecified"s into "unmarked"

**Comment by CarolinOdebrecht** [comment]
Ok.

**Comment by lb42** [comment]
Closing this, as we are in agreement!
