### ISSUE TITLE
Hungarian sample

### ISSUE THREAD

**Issue by luhpeg** [distantreading/WG1#3]
Dear All,
shall I upload a sample novel in Hungarian?

**Comment by lb42** [comment]
Yes please! Or just put a link on the wiki page

**Comment by luhpeg** [comment]
How can I edit the wiki page?

**Comment by lb42** [comment]
Good point... I have just sent you an invite.

**Comment by lb42** [comment]
Go to the wiki page http://distant reading/WG1/wiki/Example-Texts . Click the edit button top right. (You may need to login to yr github account first)
