### ISSUE TITLE
TitleStudy: Person Names pointing to Spatial Namend Entities

### ISSUE THREAD

**Issue by jberenike** [distantreading/WG1#31]
In the DEU sample there are a couple of person names that 
a) etymologically point to places (or via metnonymy to dynasties or 'houses;' like "house of Habsburg");
b) (potentially) indicate spatial (or a  more 'peagan' cultural origin/affiliation) by reference to a spatial NE 

So the question is wh/ it is relevant to flag such cases out.

DEU, e.g.:
Der Lautenbacher – case b)? The Lutebachian (but I checked the novel, no place NE "Lautenbach" mentioned)
Die Günderode –  case a)
Die letzte Reckenburgerin – probably case a)

**Comment by galleron** [comment]
Hi Berenike,
I did not realise that no one answered you on this.
We had the case in Portuguese, and did not mark up the pointers to places when they are part of a person name. It may be a debatable choice, but for consistency sake I recommend we stick to this.
Best,
Ioana

**Comment by jberenike** [comment]
Hi Iona, ok, let's do it as you recommend. b

**Comment by jberenike** [comment]
another case is Schach von Wuthenow (Wuthenow is a real town; the text features the place, but the real place it does not have the castle of the fictional world.) http://www.kirche-wuthenow.de/anhang.html#schach --- I marked Wuthenow as place!
