### ISSUE TITLE
TitleStudy: translation and transliteration of titles

### ISSUE THREAD

**Issue by CvetanaJK** [distantreading/WG1#34]
I was thinking whether we should transliterate Cyrillic titles to Latin and also translate all titles that are not in English. I think the later may be useful when writing the final report/article and also for checking the encoding. The translation need not be perfect. In case you think soemthing like that may be useful we could add two new columns at the end of the table, not to interfere with the existing columns.

**Comment by lb42** [comment]
Translation would be more useful than transliteration in my view. But why only into English?

**Comment by CarolinOdebrecht** [comment]
Englisch is sufficient, as the title-study will be written in English and we can use an Englisch version of the titles for explaining our title categories for the readers. 

I do not know whether we loose important information about the phrase structure in the titles we are also categorising if we use a proper translation. A transliteration will keep the word order for example.

**Comment by TomazErjavec** [comment]
Does this mean that the TEI docs should be changed, so we have something like:

```
<titleStmt>
  <title>Od pluga do krone : edicija ELTeC</title>
  <title xml:lang="en">From the plow to the crown : ELTeC edition</title>
   <author ref="viaf:84381657">Bedenek, Jakob (1850-1916)</author>
```
or should the translation go into the ` sourceDesc/bibl[@type="printSource"]`?

I don't think the translations should be (only) part of a separate table.

**Comment by CarolinOdebrecht** [comment]
This is for an extra study as the title should indicate. We do not intend to change the xml files. We create an extra subset for categorising titles in spreadsheets. I will create a milestone "titleStudy" that will mark every issue which is for the extra study and affects not the ELTeC data itself.

**Comment by TomazErjavec** [comment]
If new metadata is being produced, be it an extra study or not (who knows what studies will be performed on our data), then it is a shame that the metadata is not included in the TEI, where it belongs and would be available for all future studies as well. It would also be nice that everybody (that understands English) could at least know what the titles of all the novels are.
But I won't insist, up to you & I can easily leave everything as it is.

**Comment by CarolinOdebrecht** [comment]
The first step of this study was part of the Malagá program, which is accessible here https://github.com/distantreading/WG1/blob/master/MalagaMeeting2020/titlePilotStudyMalaga20202.pdf We also invited members (slides 2) to contribute. 
We annotate titles of some language collections for a first preliminary study to explore the titles. I would not think (in a first step) of these annotations as additional metadata to the documents. Of course, everything we do is available ( https://github.com/distantreading/WG1/tree/master/titlePilotStudy) and we can re-use everything for other purposes.  

I like the idea about translations for titles for ELTeC. This is something we might discuss together in another context as this might slo affect the encoding schema.

**Comment by CvetanaJK** [comment]
I also like the ides of translating titles for ELTeC, it can be useful for various purposes. But we have to be careful - translations for general ELTeC need not be the same as for this special study concentrating on titles and their structure. For instance, the French novel "Le grands Meaulnes" was translated in English as "The Last Domain" (at least some translations). For the TitleStudy we need translations that reflect the structure of the original title as much as possible (although maybe not very elegant)

**Comment by lb42** [comment]
Obviously, your study should do whatever seems right for you. But I would just comment that
(a) providing a transliteration really doesn't add anything at all in terms of comprehensibility -- it just makes it possible for a non-speaker to pronounce the title. Yes, aural info is useful, but not very!
(b) providing a translation which mimics e.g. the word order of the original is a slightly strange idea, but I can see why you might think it useful. If you decide to do it though, maybe you should mark clearly that this is not *really* English (assuming that's the target language) e.g. by saying <title type="paraphrase" xml:lang="ENG-xxx"> or similar
(c) on the other hand, if you provide the "official" translation of the title -- which might diverge considerably from the original -- you make it much easier for people to find the work in other resources, and maybe also enable other kinds of cross-cultural research, beyond the purely linguistic. Adding the info to the XML source files in this case does seem worthwhile.

**Comment by CarolinOdebrecht** [comment]
Thanks for these thoughts!
tTo be sure, we will not be working in the TEI XML files, as this requires more coordination throughout the WG. 
Maybe we can start a discussion on WG1 mailing list about translations of titles in the XML TEI files and discuss for what purpose, just as you have listed, we may need one.

**Comment by galleron** [comment]
Just to be sure that we are clear here: 
- translation of titles does not concern, in this context, the TEI files in ELTeC collections;
- it is a discussion between members of the "Title study" group;
- we don't look for perfect/ checked translations, but for some pointers (what the title is about) so as to discuss the annotation should the need be.
