### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kmihurko** [distantreading/WG1#35]
Dear All,

I am starting with the table. I have just encountered my first problem. The title of the novel is Luteranci (The Lutheran People). I am now thinking about the status: is the religious status also meant in the column Person status? Should it be explicit or also implicit (as in this case)? Would in this case the answer be yes or no? 

Best wishes,
Katja

**Comment by galleron** [comment]
Dear Katya,
Yes, the Lutherans is a status; we had "pagans" in another titles and we coded it as such.
If you wish, we can find a half a hour for a skype with you working on your collection and me helping for difficult cases.
Best,
Ioana

**Comment by kmihurko** [comment]
Dear Ioana, 
thank you! Yes, it would be great to have a Skype call for clarifying some issues in Slovenian collection. I will let you know when I gather more "problems". 
Best wishes, 
Katja 


Od: "galleron" <notifications@github.com> 
Za: "distantreading/WG1" <WG1@noreply.github.com> 
Cc: "Katja Mihurko Poniž" <katja.mihurko.poniz@ung.si>, "Author" <author@noreply.github.com> 
Poslano: Ponedeljek, 18. Maj 2020 21:16:12 
Zadeva: Re: [distantreading/WG1] Question (#35) 





Dear Katya, 
Yes, the Lutherans is a status; we had "pagans" in another titles and we coded it as such. 
If you wish, we can find a half a hour for a skype with you working on your collection and me helping for difficult cases. 
Best, 
Ioana
