### ISSUE TITLE
TitleStudy: person status?

### ISSUE THREAD

**Issue by jberenike** [distantreading/WG1#36]
dear all, 

my apologies if this has been addressed already! 
Question abt  "person status" --- is that only social/hierarchical titles like "major, lady, captain"?
Or also occupational nouns such as "the regulator" or "surveyor"?

thxs!
b

**Comment by galleron** [comment]
Hi Berenike,
We took a quite large stance here, and we accepted "pagan", "mother", and alike as "status". So in your case, "the surveyor" or the "regulator" would be the same.

**Comment by jberenike** [comment]
ok, thanks. I'm changing all personStatus for occupational nouns to "yes". But, sorry, how about
"Sonnenwirt" / Innkeeper of the Inn called "Sonne" /sun?

**Comment by galleron** [comment]
I'd annotate it as a status too. The delicate point here is to decide if it makes sense to put "Sonne" as a place - I'd rather not.
(by the way, you made me learn something, I though "wirt" means only inn, not "innkeeper". We have a similar word in Romanian, "birt", and the innkeeper will be "birtas".)

**Comment by jberenike** [comment]
thank you! Yes, there would be an ellipsis of some sort invovled, and/or metonymy. "Sonne" standing in for "Wirtshaus zur Sonne" ('inn of the sun').
