### ISSUE TITLE
TitleStudy: fictive place names?

### ISSUE THREAD

**Issue by jberenike** [distantreading/WG1#39]
e.g.,  DEU80
The title "Dumala" refers to a fictional place. But google maps does not recognize the town/place "Dumala" --> annotated as place

similar DEU70 "Wuthenow"
there is a town, but the book obviously creates a fictional version of it --> annotated as place

**Comment by jberenike** [comment]
DEU084 too

**Comment by galleron** [comment]
Yes, you should annotate them as places if you know or feel that this is the case. otherEntity is only for stuff that definitely cannot fall into the "person" or "place" category (ex. "life" in "A life").

**Comment by jberenike** [comment]
ok, thank you!
