### ISSUE TITLE
Real & Fake PlaceEntities: PlaceEntities embedded in other types of entities, attributes & else

### ISSUE THREAD

**Issue by RoxanaPatras** [distantreading/WG1#44]
Hi, everybody! 

I'm opening a discussion with a view to a more finegrained annotation of placeEntities:

1. If placeEntities are indicated in 
a. attributes such as "Russian" (placeEntity=Russia), "Moskal" (placeEntity=Moskow), Romanian (placeEntity=Romania), Italian (placeEntity=Italy)
b. compound/ synthetic nouns such as "innkeeper" (placeEntity=inn), "Sonnenwirth" (placeEntity=wirth), "Englishman" (placeEntity=England), "cabman" (placeEntity=cab)
c. derivatives of nouns indicating places (usually jobs) such as "birtas" (placeEntity=birt), "farmer" (placeEntity=farm), "villageoise" (placeEntity=village) 

then we treat them as placeEntities?

**Comment by jberenike** [comment]
... thanks for opening this issue! 
I've marked as PlaceEntities the following adjectives 
- amerikanischen (american)
- schwäbisch ( swabian )
- altmährisch (old-Moravian)
and the affix 
- bündner (grisons) from "bündnergeschichte" (grisons tale).
Found them quite clearly referring to "place". Problem for me was "placeRole": "attribute" (which I chose) or "location"? I chose attribute bc the spatial meaning is already included in placeEntity

**Comment by RoxanaPatras** [comment]
> ... thanks for opening this issue!
> I've marked as PlaceEntities the following adjectives
> 
> * amerikanischen (american)
> * schwäbisch ( swabian )
> * altmährisch (old-Moravian)
>   and the affix
> * bündner (grisons) from "bündnergeschichte" (grisons tale).
>   Found them quite clearly referring to "place". Problem for me was "placeRole": "attribute" (which I chose) or "location"? I chose attribute bc the spatial meaning is already included in placeEntity

I think it's "attribute" as well

**Comment by galleron** [comment]
We have been on the fence about this issue in the first round of annotations, Roxana, and I remember deciding rather not to annotate places in these cases. But I agree that there are arguments for doing it.  So, since there are three collections following this rule, and I agree we put it into place. Cvenata, Katja, Dmytro, is this what you have done, or would you have to revise tour entire annotation?

**Comment by DmytroYesUA** [comment]
in such/similar cases, I usually did not treat attributes and derivatives as 'placeEntity', or rather I did not extract this part of their meaning for the annotation.

Sample from Polish annotation - 'Powieść z czasów wojny franc[usko]-pruskiej' [A novel from the Franco-Prussian war]

otherEntity > wojny, otherEntityAttribution > yes

For a lonely Ukrainian similar case, 'Dvi moskovky,' I treated 'moskovky' as both personStatus and personEntity.

I am doing a revision of already submitted UA&PL annotations so can implement the change if it looks relevant

**Comment by CarolinOdebrecht** [comment]
So we include place references with multiple morphological status, e.g. nouns, adjectives, advers, right?

**Comment by kmihurko** [comment]
I would also need an answer for this. I have cases like Baltic tale, novel from Slovenian history etc. ...

**Comment by CarolinOdebrecht** [comment]
the genreIndicator is tale, novel or history - as I understand it.

**Comment by kmihurko** [comment]
yes, and what about Baltic, Slovenian? Is this a place entity?

**Comment by galleron** [comment]
Now, yes: Baltic and Slovenian point towards regions.

**Comment by CvetanaJK** [comment]
When doing Serbian collection I did not put relational adjectives like "srpski", "turski" etc, as Place entities. If we agree to do like that, I will change in my table.

**Comment by galleron** [comment]
Yes, please do so.
