### ISSUE TITLE
Date entities

### ISSUE THREAD

**Issue by CvetanaJK** [distantreading/WG1#46]
I wonder how do we treat date entities. I have cases like time period (1832-1834), years (1883 godine), cenuries (VII veka). Since we don't have a special category for them I treated "godina" (year), "vek" (century) as "otherEntity" but it does not look very informative. What would be solution for this?

**Comment by galleron** [comment]
I'm afraid you'll have to treat them as otherEntities, indeed... sniff... I pleaded the case for adding some "time" columns a few months ago, but the preliminary study showed that this category is not that much represented over the collections, so it just added lots of columns for little information gain - we've cut it.
