### ISSUE TITLE
canonical criterion

### ISSUE THREAD

**Issue by lb42** [distantreading/WG1#6]
"at least 30% are highly canonized novels, at least 30% should be non-canonized novels, based on reprints two groups: 1 Group: canon. reprinted more than once 2. Group: non-canon. not or once reprinted, period: 1980-2000"

I think we could make this a bit more objective and also improve its granularity:

canon0 - not reprinted during the author's lifetime
canon1 - reprinted up to three times after the author's death
canon2 - reprinted more than three times after the author's death

where "reprinted" means "published as a new edition", e.g. by a different publisher/in a different form etc. I feel that we shouldn't include as a reprint the digitization of a text in eg. Googlebooks, but maybe that is mistaken. The texts that appear in e.g. Gutenberg or other digital collections are in some sense chosen for their canonicity or acquire it by virtue of appearing there.

**Comment by lb42** [comment]
The sampling document also talks about "reprint count"

Reprint count
    We propose to use the number of times a work is reprinted as an objective measure of its reception, using categories like the following:
    low: reprinted less than 10 times
    medium: reprinted 10 to 100 times
    high: reprinted more than 100 times

is this the same or different? which one do we want to use?

**Comment by CarolinOdebrecht** [comment]
Thanks you very much!
We adjusted this criterion during the WG meeting in Prague (similar to the length criterion). We decided to use following: 
at least 30% are highly canonized novels, at least 30% should be non-canonized novels, based on reprints two groups: 1 Group: canon. reprinted more than once 2. Group: non-canon. not or once reprinted, period: 1980-2000
I updated the sampling document accordingly.

As for the granularity of this criterion: This might make things much more complex regarding the metadata (are we able to find out?) and the selection of texts. What if a text is not reprinted during the author's lifetime but reprinted up to three times after the author's death. This would mean that the text is at canon0 and canon1. 
As for not including text digitization into the reprint count: I think this is uncontroversial. I added a note in the sampling document to be more explicit.

**Comment by lb42** [comment]
Sorry, but this is still not clear to me. If 30% are "highly canonized" and 30% are non canonized,  what are the remaining 40%?

**Comment by christofs** [comment]
Each of the two groups is at least 30% large, but either one could be larger. So 40/60 is in keeping with this criterion, as is 30/70 or 50/50. We just don't want to have less than 30% of either type.

**Comment by lb42** [comment]
Thanks for the clarification. So the percentages are only intended as minima: e.g. a balance of 30% non canonical, 70% canonical would be OK, as would the reverse. Sorry to be dim.

**Comment by christofs** [comment]
Right! I also agree that we should clarify how this principle of "at least x %" applies to the length criterion. I like your suggestion of "at least 20% from each of the three length categories".

**Comment by CarolinOdebrecht** [comment]
The length criterion is described by "at least 20% are short novels (10-50k word tokens), at least 20% are long novels (>200k
word tokens)"
